[package]
name = "forma"
version = "0.1.0"
edition = "2024"

[dependencies]
render.workspace = true

egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
winit.workspace = true
