[package]
name = "light"
version = "0.1.0"
edition = "2024"

[dependencies]
world.workspace = true

bytemuck.workspace = true
glam = { workspace = true, features = ["bytemuck"] }
pollster.workspace = true
thiserror.workspace = true
wgpu.workspace = true
winit.workspace = true
